# What are word embeddings 
A word embedding is a learned representation for text where words that have the same meaning have a similar representation. It is this approach to representing words and documents that may be considered one of the key breakthroughs of deep learning on challenging natural language processing problems

# Word2vec Representation
Word2vec is a recently-introduced distributed word representation learning 
technique that is currently being used as a feature engineering technique for many 
NLP tasks

### Advantages 
 * The Word2vec approach is not subjective to the human knowledge of language as in the WordNet-based approach.
 * Word2vec representation vector size is independent of the vocabulary size unlike one-hot encoded representation or the word co-occurrence matrix
 * Word2vec is a distributed representation. Unlike localist representation, where the representation depends on the activation of a single element of the representation vector (for example, one-hot encoding), the distributed representation depends on the activation pattern of all the elements in the vector. This gives more expressive power to Word2vec than produced by the one-hot encoded representation
 
### Main idea 
Word2vec learns the meaning of a given word by looking at its context and representing it numerically. By context, we refer to a fixed number of words in front of and behind the word of interest. 

# The continous bad of words model 
The CBOW model architecture tries to predict the current target word (the center word) based on the source context words (surrounding words).

Considering a simple sentence, “the quick brown fox jumps over the lazy dog”, this can be pairs of (context_window, target_word) where if we consider a context window of size 2, we have examples like ([quick, fox], brown), ([the, brown], quick), ([the, dog], lazy) and so on. Thus the model tries to predict the target_word based on the context_window words

<img src = 'https://www.researchgate.net/profile/Daniel-Braun-6/publication/326588219/figure/fig1/AS:652185784295425@1532504616288/Continuous-Bag-of-words-CBOW-CB-and-Skip-gram-SG-training-model-illustrations.png'>

In [13]:
from keras.preprocessing.text import one_hot

In [14]:
import tensorflow

In [17]:
tensorflow.__version__

'2.6.0'

In [20]:
corpus =[
    'the glass of milk',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of words'   
]

In [51]:
voc_size  =1000
labels = np.array([1,1,0,0,2])

In [23]:
onehot = [one_hot(words,voc_size) for words in corpus]
onehot  # getting the index representation 

[[993, 994, 635, 701],
 [993, 215, 635, 379],
 [363, 424, 635, 788, 456],
 [363, 424, 635, 788, 203],
 [198, 993, 246, 635, 526]]

# Word embedding representation 

In [26]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences 
from keras.models import Sequential

In [27]:
import numpy as np 

In [28]:
sent_length = 8 
embedded_docs = pad_sequences(onehot, padding = 'pre', maxlen = sent_length) 
print(embedded_docs)

[[  0   0   0   0 993 994 635 701]
 [  0   0   0   0 993 215 635 379]
 [  0   0   0 363 424 635 788 456]
 [  0   0   0 363 424 635 788 203]
 [  0   0   0 198 993 246 635 526]]


In [45]:
dim = 10
from keras.layers import Flatten
from keras.layers import Dense

In [53]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.add(Flatten()) 
model.add(Dense(2,activation = 'softmax')) 
model.compile('adam','categorical_crossentropy', metrics = ['accuracy'])

In [54]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 8, 10)             10000     
_________________________________________________________________
flatten_2 (Flatten)          (None, 80)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 162       
Total params: 10,162
Trainable params: 10,162
Non-trainable params: 0
_________________________________________________________________


In [55]:
embedded_docs[0]

array([  0,   0,   0,   0, 993, 994, 635, 701])

In [56]:
model.fit(embedded_docs,labels,epochs = 10 )

Epoch 1/10


ValueError: in user code:

    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\engine\training.py:853 train_function  *
        return step_function(self, iterator)
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\engine\training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\ASUS\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\ASUS\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\ASUS\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\engine\training.py:835 run_step  **
        outputs = model.train_step(data)
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\engine\training.py:788 train_step
        loss = self.compiled_loss(
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\engine\compile_utils.py:201 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\losses.py:141 __call__
        losses = call_fn(y_true, y_pred)
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\losses.py:245 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    C:\Users\ASUS\anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\losses.py:1665 categorical_crossentropy
        return backend.categorical_crossentropy(
    C:\Users\ASUS\anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\keras\backend.py:4839 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    C:\Users\ASUS\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py:1161 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 2) are incompatible
